#!/usr/bin/env python3
"""
run_wp2d.py — WP-2d: circularity indicators, frozen-time vs non-autonomous
==========================================================================

The highest-value result in WP-2, and the one Chapter 2 poses but cannot
evaluate.  On the estimated A(t) of WP-2a, both forms of Chapter 2's
circularity indicators are computed at every year node and every seed, and the
**discrepancy between them is reported** — which quantifies the frozen-time
approximation error and is a methodological contribution back to Chapter 2,
possible only because Chapter 4 supplies an empirical A(t).

Frozen-time                                  # Ch2 Eq. frozen_time_circularity
    tau^fr_i(t)     = 1^T [-A_FD(t)]^-1 e_i
    upsilon^fr_i(t) = c_use(t)^T [-A_FD(t)]^-1 e_i

Non-autonomous, Phi(t0+u, t0) generated by the fitted A_FD(t)
                                             # Ch2 Eq. nonautonomous_lifetime
    tau_FD,i(t0)    = int_0^inf 1^T Phi(t0+u, t0) e_i du
                                             # Ch2 Eq. nonautonomous_use_count
    upsilon_i(t0)   = int_0^inf c_use(t0+u)^T Phi(t0+u, t0) e_i du

with `A_FD(t) = A(t)` and `alpha_8 e_3^T -> c_use(t)^T` as set out in
`zinc_circ_lab` (the UDE has no landfill state, and entry into use is fed by
two stocks because Chapter 2's s_2 and s_3 are aggregated).  The same pair is
computed for the two old-scrap return routes, Chapter 2's `Upsilon_13` and
`Upsilon_14` (Eq. old_scrap_count_appendix) — i.e. for `alpha_dr` and
`alpha_win`, the coefficients the whole circularity argument rests on.

Elasticities `S_tau,l` and `S_upsilon,l` (Ch2 Eq. tau_U_elasticities) are
reported alongside; the full sensitivity matrices behind them are WP-2e.

Coefficients beyond the sample window
-------------------------------------
`Phi` needs A(t) over the whole absorption horizon, so a rule is required.
Four are run and compared (`zinc_circ_lab.coeff_path`):
  `hold`     freeze at the 2019 node — the reference rule;
  `mean5`    freeze at the mean of the last five nodes;
  `trend20`  continue the fitted 10-year trend for 20 yr, then freeze;
  `trend50`  the same for 50 yr — a deliberate stress test.
Beyond `t_switch` every rule is constant, so the infinite tail is closed in
**closed form** (`c^T N_const Phi(t_switch)`) rather than truncated.  The
sensitivity of every reported number to the choice is in
`wp2d_rule_sensitivity.csv`.

    python run_wp2d.py --check
    python run_wp2d.py
"""

from __future__ import annotations

import argparse
import hashlib
import os
import sys

import numpy as np
import pandas as pd

import zinc_circ_lab as L

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(HERE, "analysis")
A_NPZ = os.path.join(OUT_DIR, "wp2a_A_of_t.npz")

STATE = list(L.ODE_STATE_NAMES)
COL = ["#0072B2", "#009E73", "#D55E00", "#CC79A7", "#E69F00", "#56B4E9"]
RULE_COL = {"hold": "#0072B2", "mean5": "#009E73",
            "trend20": "#D55E00", "trend50": "#CC79A7"}
GREY = "#555555"
REF_RULE = "hold"
N_SUB = 64
START = 0                       # headline starting stock: S_conc


def load(path=A_NPZ):
    if not os.path.exists(path):
        raise SystemExit(f"{path} not found — run run_wp2a.py first")
    d = np.load(path, allow_pickle=True)
    return d, hashlib.md5(open(path, "rb").read()).hexdigest()


# ---------------------------------------------------------------------------
# validation: an independent reference integrator
# ---------------------------------------------------------------------------
def reference_integration(P, years, seed_idx, t0_idx, rule=REF_RULE):
    """`tau` and the flow counts at one (seed, t0) from `scipy.solve_ivp` at
    tight tolerance, integrating the 6x6 Phi ODE and its accumulators directly
    off `coeff_path`.

    Independent of the exponential-midpoint scheme in `zinc_circ_lab`: a
    different quadrature, a different step-size controller and a different
    evaluation of A(t).  Only the closed-form tail is shared, and that term is
    exact.
    """
    from scipy.integrate import solve_ivp

    Pn = P[seed_idx:seed_idx + 1]
    t0 = years[t0_idx]
    _, t_switch = L.coeff_path(Pn, years, np.array([years[-1]]), rule=rule)
    nf = len(L.FLOW_NAMES)

    def rhs(u, z):
        Pt, _ = L.coeff_path(Pn, years, np.array([t0 + u]), rule=rule)
        A = L.assemble_from_params(Pt)[0, 0]
        c = {k: v[0] for k, v in L.flow_rows(A[None]).items()}
        Phi = z[:36].reshape(6, 6)
        out = np.empty_like(z)
        out[:36] = (A @ Phi).ravel()
        out[36:42] = np.ones(6) @ Phi
        for j, k in enumerate(L.FLOW_NAMES):
            out[42 + 6 * j: 48 + 6 * j] = c[k] @ Phi
        return out

    z0 = np.zeros(36 + 6 * (1 + nf))
    z0[:36] = np.eye(6).ravel()
    U = float(t_switch - t0)
    if U > 0:
        sol = solve_ivp(rhs, (0.0, U), z0, method="LSODA",
                        rtol=1e-11, atol=1e-13, dense_output=False)
        z = sol.y[:, -1]
    else:
        z = z0
    Phi = z[:36].reshape(6, 6)
    Pe, _ = L.coeff_path(Pn, years, np.array([t_switch + 1.0]), rule=rule)
    Ae = L.assemble_from_params(Pe)[0, 0]
    Ne = L.fundamental(Ae[None], on_singular="nan")[0]
    ce = {k: v[0, 0] for k, v in L.flow_rows(Ae[None, None]).items()}
    tau = z[36:42] + np.ones(6) @ Ne @ Phi
    counts = {k: z[42 + 6 * j: 48 + 6 * j] + ce[k] @ Ne @ Phi
              for j, k in enumerate(L.FLOW_NAMES)}
    return tau, counts


# ---------------------------------------------------------------------------
# tables
# ---------------------------------------------------------------------------
def indicator_table(frozen, nonauto, years, seeds):
    """Median/IQR across seeds, per (year, start stock, indicator, form)."""
    rows = []
    items = [("tau_FD", frozen["tau"], {r: v["tau"] for r, v in nonauto.items()})]
    for k in L.FLOW_NAMES:
        items.append((k, frozen["counts"][k],
                      {r: v["counts"][k] for r, v in nonauto.items()}))
    for name, fr, na in items:
        for i in range(6):
            for ti, y in enumerate(years):
                q = np.nanpercentile(fr[:, ti, i], [25, 50, 75])
                rows.append(dict(indicator=name, start_stock=STATE[i],
                                 year=float(y), form="frozen", rule="",
                                 median=q[1], q1=q[0], q3=q[2],
                                 n_seeds=int(np.isfinite(fr[:, ti, i]).sum())))
                for rule, v in na.items():
                    q = np.nanpercentile(v[:, ti, i], [25, 50, 75])
                    rows.append(dict(
                        indicator=name, start_stock=STATE[i], year=float(y),
                        form="nonautonomous", rule=rule,
                        median=q[1], q1=q[0], q3=q[2],
                        n_seeds=int(np.isfinite(v[:, ti, i]).sum())))
    return pd.DataFrame(rows)


def discrepancy_table(frozen, nonauto, years):
    """The headline object: non-autonomous minus frozen, seed-paired.

    Reported in native units and as a fraction of the frozen value, with a
    Hodges-Lehmann interval over the 35 seeds (project convention: HL
    intervals, not significance tests).
    """
    rows = []
    items = [("tau_FD", frozen["tau"], {r: v["tau"] for r, v in nonauto.items()})]
    for k in L.FLOW_NAMES:
        items.append((k, frozen["counts"][k],
                      {r: v["counts"][k] for r, v in nonauto.items()}))
    for name, fr, na in items:
        for rule, v in na.items():
            for i in range(6):
                for ti, y in enumerate(years):
                    dif = v[:, ti, i] - fr[:, ti, i]
                    rel = dif / fr[:, ti, i]
                    h = L.hodges_lehmann(dif)
                    hr = L.hodges_lehmann(rel)
                    rows.append(dict(
                        indicator=name, rule=rule, start_stock=STATE[i],
                        year=float(y),
                        frozen_median=float(np.nanmedian(fr[:, ti, i])),
                        nonauto_median=float(np.nanmedian(v[:, ti, i])),
                        abs_diff_hl=h["hl"], abs_diff_lo=h["lo"],
                        abs_diff_hi=h["hi"],
                        rel_diff_hl=hr["hl"], rel_diff_lo=hr["lo"],
                        rel_diff_hi=hr["hi"], n_seeds=h["n"]))
    return pd.DataFrame(rows)


# ---------------------------------------------------------------------------
# figures
# ---------------------------------------------------------------------------
def fig_circularity(frozen, nonauto, years, mask_test, path):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    t0 = float(years[np.asarray(mask_test, bool)][0])
    fig, axes = plt.subplots(2, 2, figsize=(12.0, 8.0))

    def band(ax, X, colour, label, ls="-"):
        lo, med, hi = np.nanpercentile(X, [25, 50, 75], axis=0)
        ax.fill_between(years, lo, hi, color=colour, alpha=0.18, lw=0)
        ax.plot(years, med, color=colour, lw=1.8, ls=ls, label=label)

    # (a) technological lifetime
    ax = axes[0, 0]
    band(ax, frozen["tau"][:, :, START], "k", r"frozen  $\tau^{fr}_1(t)$",
         ls="--")
    for rule, v in nonauto.items():
        band(ax, v["tau"][:, :, START], RULE_COL[rule],
             rf"non-autonomous, {rule}")
    ax.set_ylabel("yr")
    ax.set_title(r"(a) technological lifetime $\tau_{FD,1}$"
                 "\n     Ch2 Eq. frozen_time_circularity vs "
                 "Eq. nonautonomous_lifetime", loc="left", fontsize=9)
    ax.legend(fontsize=6.5, frameon=False, ncol=2)

    # (b) expected use episodes
    ax = axes[0, 1]
    band(ax, frozen["counts"]["use_entry"][:, :, START], "k",
         r"frozen  $\upsilon^{fr}_1(t)$", ls="--")
    for rule, v in nonauto.items():
        band(ax, v["counts"]["use_entry"][:, :, START], RULE_COL[rule], rule)
    ax.set_ylabel("expected entries into use")
    ax.set_title(r"(b) expected use count $\upsilon_1$"
                 "\n     Ch2 Eq. nonautonomous_use_count", loc="left",
                 fontsize=9)
    ax.legend(fontsize=6.5, frameon=False, ncol=2)

    # (c) the discrepancy, relative
    ax = axes[1, 0]
    for rule, v in nonauto.items():
        rel = (v["tau"][:, :, START] - frozen["tau"][:, :, START]) / \
            frozen["tau"][:, :, START]
        band(ax, 100 * rel, RULE_COL[rule], rf"$\tau$, {rule}")
    rel = (nonauto[REF_RULE]["counts"]["use_entry"][:, :, START]
           - frozen["counts"]["use_entry"][:, :, START]) / \
        frozen["counts"]["use_entry"][:, :, START]
    band(ax, 100 * rel, "#000000", rf"$\upsilon$, {REF_RULE}", ls=":")
    ax.axhline(0, color="k", lw=0.8)
    ax.set_ylabel("non-autonomous − frozen  (% of frozen)")
    ax.set_title("(c) the frozen-time approximation error", loc="left",
                 fontsize=9.5)
    ax.legend(fontsize=6.5, frameon=False, ncol=2)

    # (d) the two old-scrap routes
    ax = axes[1, 1]
    for k, c, lab in (("oldscrap_manufacture", COL[0],
                       r"$\Upsilon_{13}$  alpha_dr"),
                      ("oldscrap_metallurgy", COL[2],
                       r"$\Upsilon_{14}$  alpha_win")):
        band(ax, frozen["counts"][k][:, :, START], c, lab + "  frozen",
             ls="--")
        band(ax, nonauto[REF_RULE]["counts"][k][:, :, START], c,
             lab + "  non-aut.")
    ax.set_ylabel("expected old-scrap returns")
    ax.set_title(r"(d) the two Ch2 circularity routes, $\Upsilon_{13}$ vs "
                 r"$\Upsilon_{14}$", loc="left", fontsize=9.5)
    ax.legend(fontsize=6.5, frameon=False, ncol=2)

    for ax in axes.ravel():
        ax.axvline(t0, color=GREY, lw=0.9, ls=":")
        ax.spines[["top", "right"]].set_visible(False)
        ax.grid(lw=0.4, alpha=0.3)
        ax.set_xlabel(r"$t_0$  (year)")
    fig.suptitle("WP-2d  circularity indicators on the estimated A(t) — "
                 "anchor_v4, 35 seeds (median, IQR); "
                 "start stock = S_conc; dotted vline = held-out window",
                 fontsize=11, x=0.01, ha="left")
    fig.tight_layout(rect=(0, 0, 1, 0.95))
    fig.savefig(path, dpi=300)
    fig.savefig(path.replace(".png", ".pdf"))
    plt.close(fig)


def fig_elasticities(el, years, path):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    fig, axes = plt.subplots(1, 2, figsize=(12.0, 5.2))
    for ax, ind, title in (
            (axes[0], "tau_FD", r"$S_{\tau,l}$ — technological lifetime"),
            (axes[1], "use_entry", r"$S_{\upsilon,l}$ — expected use count")):
        sub = el[(el.indicator == ind) & (el.start_stock == STATE[START])]
        last = sub[sub.year == years[-1]].set_index("param")
        first = sub[sub.year == years[0]].set_index("param")
        rank = last.elasticity_median.abs().sort_values().index[-10:]
        y = np.arange(len(rank))
        ax.barh(y - 0.19, first.loc[rank, "elasticity_median"], height=0.36,
                color="#56B4E9", label=f"{years[0]:.0f}")
        ax.barh(y + 0.19, last.loc[rank, "elasticity_median"], height=0.36,
                color="#0072B2", label=f"{years[-1]:.0f}")
        for i, p in enumerate(rank):
            ax.plot([last.loc[p, "elasticity_q1"], last.loc[p, "elasticity_q3"]],
                    [i + 0.19, i + 0.19], color="k", lw=1.0)
        ax.set_yticks(y)
        ax.set_yticklabels(list(rank), fontsize=7.5)
        ax.axvline(0, color="k", lw=0.8)
        ax.set_xlabel("elasticity")
        ax.set_title(title, loc="left", fontsize=10)
        ax.spines[["top", "right"]].set_visible(False)
        ax.grid(axis="x", lw=0.4, alpha=0.3)
        ax.legend(fontsize=8, frameon=False, loc="lower right")
    fig.suptitle("WP-2d  frozen-time indicator elasticities "
                 "(Ch2 Eq. tau_U_elasticities), start stock = S_conc — "
                 "seed median (bar), IQR (line)", fontsize=11, x=0.01,
                 ha="left")
    fig.tight_layout(rect=(0, 0, 1, 0.92))
    fig.savefig(path, dpi=300)
    fig.savefig(path.replace(".png", ".pdf"))
    plt.close(fig)


# ---------------------------------------------------------------------------
def main(argv=None):
    ap = argparse.ArgumentParser(
        description="WP-2d: frozen-time vs non-autonomous circularity")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--npz", default=A_NPZ)
    ap.add_argument("--out", default=OUT_DIR)
    ap.add_argument("--n-sub", type=int, default=N_SUB)
    args = ap.parse_args(argv)

    L.check(verbose=True)
    if args.check:
        return 0

    d, md5 = load(args.npz)
    A = np.asarray(d["A"], float)
    years = np.asarray(d["years"], float)
    seeds = np.asarray(d["seeds"], int)
    mu = np.asarray(d["mu_cohorts"], float)
    S, T = A.shape[:2]
    P = L.pack_params(d, mu)
    print(f"\nloaded {os.path.basename(args.npz)}  md5 {md5}")
    print(f"  A {A.shape}  seeds {S}  years {years[0]:.0f}-{years[-1]:.0f}")
    print(f"  A_FD(t) = A(t): the UDE has no landfill state, so the 6-state "
          f"IS Ch2's transient space")

    # --- frozen-time --------------------------------------------------------
    tau_fr, cnt_fr, N = L.frozen_indicators(A)
    frozen = dict(tau=tau_fr, counts=cnt_fr)
    print(f"\n--- frozen-time (Ch2 Eq. frozen_time_circularity) ---")
    print(f"  -A is an M-matrix at all {S*T} nodes: min N entry "
          f"{N.min():.3e} (must be >= 0), max spectral abscissa "
          f"{L.spectral_abscissa(A).max():+.5f} /yr")
    for i in (0, 1, 5):
        a = np.percentile(tau_fr[:, 0, i], [50, 25, 75])
        b = np.percentile(tau_fr[:, -1, i], [50, 25, 75])
        print(f"  tau^fr from {STATE[i]:<11s} {years[0]:.0f} {a[0]:7.2f} yr "
              f"[{a[1]:.2f},{a[2]:.2f}]   {years[-1]:.0f} {b[0]:7.2f} yr "
              f"[{b[1]:.2f},{b[2]:.2f}]")
    for k in L.FLOW_NAMES:
        a = np.percentile(cnt_fr[k][:, 0, START], [50, 25, 75])
        b = np.percentile(cnt_fr[k][:, -1, START], [50, 25, 75])
        print(f"  {k:<21s} ({L.FLOW_CH2[k]:<14s}) from {STATE[START]}: "
              f"{a[0]:.4f} [{a[1]:.4f},{a[2]:.4f}] -> "
              f"{b[0]:.4f} [{b[1]:.4f},{b[2]:.4f}]")
    pu = L.prob_reaches_use(A)
    a = np.percentile(pu[:, 0, START], [50, 25, 75])
    b = np.percentile(pu[:, -1, START], [50, 25, 75])
    cond0 = cnt_fr["use_entry"][:, 0, START] / pu[:, 0, START]
    cond1 = cnt_fr["use_entry"][:, -1, START] / pu[:, -1, START]
    print(f"  P^use (Ch2 Eq. prob_use_appendix) from {STATE[START]}: "
          f"{a[0]:.4f} [{a[1]:.4f},{a[2]:.4f}] -> "
          f"{b[0]:.4f} [{b[1]:.4f},{b[2]:.4f}]")
    print(f"  conditional use episodes upsilon_1/P^use "
          f"(Ch2 Eq. conditional_use_appendix): "
          f"{np.median(cond0):.4f} -> {np.median(cond1):.4f}")

    # --- non-autonomous -----------------------------------------------------
    print(f"\n--- non-autonomous (Ch2 Eq. nonautonomous_lifetime / "
          f"_use_count), n_sub = {args.n_sub}/yr ---")
    nonauto = {}
    for rule in L.RULES:
        r = L.nonautonomous_indicators(P, years, rule=rule, n_sub=args.n_sub)
        nonauto[rule] = r
        ns = int(r["end_stable"].sum())
        print(f"  {rule:<8s} t_switch {r['t_switch']:.0f}  "
              f"{r['n_steps']} substeps  closed-form tail carries "
              f"{100*np.median(r['tail_share_tau'][:, 0, START]):.1f}% of "
              f"tau_1({years[0]:.0f})   terminal system asymptotically "
              f"stable for {ns}/{S} seeds")
        if ns < S:
            bad = seeds[~r["end_stable"]]
            print(f"    !! seeds {bad.tolist()} lose their absorbing boundary "
                  f"under this rule (tau_waelz and tau_ref clip at their\n"
                  f"       feasible bounds, so the stock has no exit): the "
                  f"lifetime genuinely diverges and is reported as NaN, not "
                  f"suppressed.")

    # --- validation ---------------------------------------------------------
    print("\n--- validation ---")
    r_hi = L.nonautonomous_indicators(P, years, rule=REF_RULE,
                                      n_sub=2 * args.n_sub)
    rel_h = float(np.nanmax(np.abs(nonauto[REF_RULE]["tau"] - r_hi["tau"]))
                  / np.nanmax(np.abs(r_hi["tau"])))
    print(f"  step halving {args.n_sub} -> {2*args.n_sub}/yr: max rel change "
          f"in tau {rel_h:.2e}  (2nd-order scheme, so the error at "
          f"{2*args.n_sub}/yr is ~{rel_h/3:.1e})")
    term = float(np.max(np.abs(nonauto["hold"]["tau"][:, -1] - tau_fr[:, -1])))
    term_u = float(np.max(np.abs(
        nonauto["hold"]["counts"]["use_entry"][:, -1]
        - cnt_fr["use_entry"][:, -1])))
    print(f"  terminal-node identity under `hold` (A is constant beyond "
          f"{years[-1]:.0f}, so the two forms must coincide at "
          f"t_0 = {years[-1]:.0f}):")
    print(f"    max |tau_nonauto - tau^fr| = {term:.3e};  "
          f"max |upsilon - upsilon^fr| = {term_u:.3e}   (exact answer 0)")
    ref_rows = []
    for si, ti in ((0, 0), (0, 20), (17, 5), (34, 30)):
        tref, cref = reference_integration(P, years, si, ti)
        e_t = float(np.max(np.abs(tref - nonauto[REF_RULE]["tau"][si, ti])))
        e_c = float(np.max(np.abs(
            cref["use_entry"] - nonauto[REF_RULE]["counts"]["use_entry"][si, ti])))
        ref_rows.append(dict(seed=int(seeds[si]), year=float(years[ti]),
                             max_abs_err_tau=e_t, max_abs_err_upsilon=e_c,
                             rel_err_tau=e_t / float(np.abs(tref).max())))
        print(f"  vs LSODA reference (rtol 1e-11) seed {seeds[si]} "
              f"t0 {years[ti]:.0f}: max |dtau| = {e_t:.2e} yr "
              f"({100*e_t/np.abs(tref).max():.4f}%), "
              f"max |dupsilon| = {e_c:.2e}")
    pd.DataFrame(
        [dict(check="step_halving_max_rel_change_tau", value=rel_h),
         dict(check="terminal_identity_max_abs_tau", value=term),
         dict(check="terminal_identity_max_abs_upsilon", value=term_u),
         dict(check="min_N_entry_frozen", value=float(N.min())),
         dict(check="max_spectral_abscissa_in_window",
              value=float(L.spectral_abscissa(A).max()))]
        + [dict(check=f"reference_lsoda_seed{r['seed']}_y{int(r['year'])}"
                      f"_max_abs_err_tau", value=r["max_abs_err_tau"])
           for r in ref_rows]).to_csv(
        os.path.join(args.out, "wp2d_validation.csv"), index=False)

    # --- the headline: the discrepancy --------------------------------------
    disc = discrepancy_table(frozen, nonauto, years)
    print("\n=== the frozen-time approximation error "
          "(non-autonomous - frozen, seed-paired HL) ===")
    for ind, lab in (("tau_FD", "technological lifetime  tau_FD,1  (yr)"),
                     ("use_entry", "expected use count      upsilon_1")):
        sub = disc[(disc.indicator == ind) & (disc.rule == REF_RULE)
                   & (disc.start_stock == STATE[START])]
        print(f"  {lab}")
        for y in (years[0], years[len(years) // 2], years[-1]):
            r = sub[sub.year == y].iloc[0]
            print(f"    {y:.0f}  frozen {r.frozen_median:8.4f}   "
                  f"non-aut. {r.nonauto_median:8.4f}   "
                  f"diff {r.abs_diff_hl:+8.4f} "
                  f"[{r.abs_diff_lo:+.4f},{r.abs_diff_hi:+.4f}]   "
                  f"{100*r.rel_diff_hl:+6.2f}% "
                  f"[{100*r.rel_diff_lo:+.2f},{100*r.rel_diff_hi:+.2f}]")
        tr = sub[sub.year <= years[-1] - 10]
        print(f"    mean |relative error| over t0 <= {years[-1]-10:.0f}: "
              f"{100*np.abs(tr.rel_diff_hl).mean():.2f}%   "
              f"max {100*np.abs(tr.rel_diff_hl).max():.2f}%")

    print(f"\n  all indicators, |relative error| of the frozen form under "
          f"`{REF_RULE}`, over t0 <= {years[-1]-10:.0f}:")
    for ind in ["tau_FD"] + L.FLOW_NAMES:
        sub = disc[(disc.indicator == ind) & (disc.rule == REF_RULE)
                   & (disc.start_stock == STATE[START])
                   & (disc.year <= years[-1] - 10)]
        print(f"    {ind:<21s} mean {100*np.abs(sub.rel_diff_hl).mean():6.2f}%"
              f"   max {100*np.abs(sub.rel_diff_hl).max():6.2f}%"
              f"   sign {'+' if (sub.rel_diff_hl > 0).all() else 'mixed'}")

    print("\n  the two old-scrap routes (Ch2 Eq. old_scrap_count_appendix):")
    for k in ("oldscrap_manufacture", "oldscrap_metallurgy"):
        sub = disc[(disc.indicator == k) & (disc.rule == REF_RULE)
                   & (disc.start_stock == STATE[START])]
        r0 = sub[sub.year == years[0]].iloc[0]
        print(f"    {k:<21s} ({L.FLOW_CH2[k]}) {years[0]:.0f}: frozen "
              f"{r0.frozen_median:.4f} -> non-aut. {r0.nonauto_median:.4f}  "
              f"({100*r0.rel_diff_hl:+.2f}% "
              f"[{100*r0.rel_diff_lo:+.2f},{100*r0.rel_diff_hi:+.2f}])")

    # --- sensitivity to the extrapolation rule ------------------------------
    print("\n--- sensitivity to the extrapolation rule (spec: 'document it "
          "and test sensitivity to the choice') ---")
    rule_rows = []
    all_arrs = [("tau_FD", {r: v["tau"] for r, v in nonauto.items()})]
    all_arrs += [(k, {r: v["counts"][k] for r, v in nonauto.items()})
                 for k in L.FLOW_NAMES]
    for ind, arrs in all_arrs:
        for ti, y in enumerate(years):
            vals = {r: float(np.nanmedian(v[:, ti, START]))
                    for r, v in arrs.items()}
            spread = max(vals.values()) - min(vals.values())
            base = vals[REF_RULE]
            rule_rows.append(dict(indicator=ind, year=float(y),
                                  spread_abs=spread, spread_rel=spread / base,
                                  **{f"median_{r}": v for r, v in vals.items()}))
        rr = pd.DataFrame([r for r in rule_rows if r["indicator"] == ind])
        print(f"  {ind:<21s} across-rule spread of the seed median, as a "
              f"fraction of `{REF_RULE}`: median "
              f"{100*rr.spread_rel.median():5.2f}%, max "
              f"{100*rr.spread_rel.max():5.2f}% (in "
              f"{int(rr.loc[rr.spread_rel.idxmax(), 'year'])})")

    # Is the frozen-vs-non-autonomous gap larger than the ambiguity in the
    # extrapolation rule?  If not, the discrepancy is not reportable.
    print(f"\n  discrepancy vs rule ambiguity, at t0 = {years[0]:.0f}, from "
          f"{STATE[START]}:")
    print(f"    {'indicator':<21s} {'rule':<9s} {'frozen':>9s} "
          f"{'non-aut.':>9s} {'rel diff':>10s}")
    for ind, _ in all_arrs:
        for rule in L.RULES:
            r = disc[(disc.indicator == ind) & (disc.rule == rule)
                     & (disc.start_stock == STATE[START])
                     & (disc.year == years[0])].iloc[0]
            print(f"    {ind if rule == L.RULES[0] else '':<21s} {rule:<9s} "
                  f"{r.frozen_median:9.4f} {r.nonauto_median:9.4f} "
                  f"{100*r.rel_diff_hl:+9.2f}%")
    pd.DataFrame(rule_rows).to_csv(
        os.path.join(args.out, "wp2d_rule_sensitivity.csv"), index=False)

    # --- elasticities  (Ch2 Eq. tau_U_elasticities) -------------------------
    dA = L.dA_dparams(P)
    el_rows = []
    dtau, dcounts, _ = L.indicator_sensitivity(A, dA)
    tau_v, cnt_v, _ = L.frozen_indicators(A)
    for n in range(L.N_PARAM):
        for i in range(6):
            for ti, y in enumerate(years):
                p = P[:, ti, n]
                def stats(dv, v):
                    e = p * dv / np.where(np.abs(v) > 0, v, np.nan)
                    q = np.nanpercentile(e, [25, 50, 75])
                    dq = np.nanpercentile(dv, [25, 50, 75])
                    return dict(elasticity_median=q[1], elasticity_q1=q[0],
                                elasticity_q3=q[2], derivative_median=dq[1],
                                derivative_q1=dq[0], derivative_q3=dq[2])
                el_rows.append(dict(indicator="tau_FD",
                                    param=L.PARAM_NAMES[n],
                                    start_stock=STATE[i], year=float(y),
                                    **stats(dtau[:, ti, n, i], tau_v[:, ti, i])))
                for k in L.FLOW_NAMES:
                    el_rows.append(dict(indicator=k, param=L.PARAM_NAMES[n],
                                        start_stock=STATE[i], year=float(y),
                                        **stats(dcounts[k][:, ti, n, i],
                                                cnt_v[k][:, ti, i])))
    el = pd.DataFrame(el_rows)
    print("\n--- elasticities S_tau,l and S_upsilon,l "
          "(Ch2 Eq. tau_U_elasticities), from S_conc, 2019 ---")
    for ind, lab in (("tau_FD", "S_tau,l "), ("use_entry", "S_ups,l")):
        sub = el[(el.indicator == ind) & (el.start_stock == STATE[START])
                 & (el.year == years[-1])]
        top = sub.reindex(sub.elasticity_median.abs().sort_values(
            ascending=False).index)[:6]
        for _, r in top.iterrows():
            print(f"  {lab} {r.param:<16s} {r.elasticity_median:+8.4f} "
                  f"[{r.elasticity_q1:+.4f},{r.elasticity_q3:+.4f}]")

    # --- conditioning: the frozen form is also noisier ----------------------
    # A second, unforced consequence of reading the frozen form: it evaluates
    # a whole absorption horizon at one year's coefficients, so year-on-year
    # jitter in the fitted coefficients passes straight through, while the
    # non-autonomous form integrates over the future path and averages it out.
    print("\n--- conditioning of the two forms ---")
    cond_rows = []
    for ind, fr, na in (("tau_FD", tau_fr[:, :, START],
                         nonauto[REF_RULE]["tau"][:, :, START]),
                        ("use_entry", cnt_fr["use_entry"][:, :, START],
                         nonauto[REF_RULE]["counts"]["use_entry"][:, :, START])):
        ra = np.abs(np.diff(fr, axis=1)).mean(1) / np.abs(fr).mean(1)
        rb = np.abs(np.diff(na, axis=1)).mean(1) / np.abs(na).mean(1)
        h = L.hodges_lehmann(ra - rb)
        cond_rows.append(dict(indicator=ind,
                              roughness_frozen=float(np.median(ra)),
                              roughness_nonautonomous=float(np.median(rb)),
                              ratio=float(np.median(ra / rb)),
                              hl=h["hl"], lo=h["lo"], hi=h["hi"]))
        print(f"  {ind:<10s} mean |year-on-year| / mean level: frozen "
              f"{100*np.median(ra):5.2f}%   non-autonomous "
              f"{100*np.median(rb):5.2f}%   ratio {np.median(ra/rb):.2f}x  "
              f"(HL {100*h['hl']:+.2f} pp [{100*h['lo']:+.2f},"
              f"{100*h['hi']:+.2f}])")
    pd.DataFrame(cond_rows).to_csv(
        os.path.join(args.out, "wp2d_conditioning.csv"), index=False)

    # --- Chapter 2's alpha_13 vs alpha_14 ranking, tested -------------------
    # Ch2 (Sec. tab:tau_U_sensitivities) states: "Increasing old-scrap returns
    # through alpha_13 and alpha_14 raises both indicators, with the return to
    # metallurgy having the stronger normalised effect in the current
    # parameterisation."  That parameterisation is copper and assumed; this is
    # the first empirical test of the ranking.
    #
    # The unconstrained partials are the wrong test.  In the UDE the loss on
    # each old-scrap route is a fixed share of that same route's flow
    # ((1 - tau_waelz) on the metallurgy route, the manufacturing loss share
    # on the direct-reuse route), and there is no landfill state to divert
    # material away from (mapping decision 1).  Raising a gross rate therefore
    # raises return and loss together.  The well-posed question is the
    # *split*: Ch2's own directional-derivative device, applied to the two
    # routes out of S_scrap at a fixed combined rate.
    print("\n=== Ch2's alpha_13 vs alpha_14 ranking, tested on the "
          "estimated A(t) ===")
    nd = L.PARAM_NAMES.index("alpha_dr")
    nw = L.PARAM_NAMES.index("alpha_win")
    ch2_rows = []
    for ti, y in ((0, years[0]), (T - 1, years[-1])):
        tot = P[:, ti, nw] + P[:, ti, nd]
        for ind, dv, v in (("tau_FD", dtau[:, ti, :, START], tau_fr[:, ti, START]),
                           ("use_entry", dcounts["use_entry"][:, ti, :, START],
                            cnt_fr["use_entry"][:, ti, START])):
            step = 0.01 * tot                    # +1% of the combined rate
            h = L.hodges_lehmann((dv[:, nw] - dv[:, nd]) * step)
            hr = L.hodges_lehmann((dv[:, nw] - dv[:, nd]) * step / v)
            ch2_rows.append(dict(
                year=float(y), indicator=ind,
                direction="alpha_win <- alpha_dr (metallurgy <- direct reuse)",
                d_indicator_hl=h["hl"], d_indicator_lo=h["lo"],
                d_indicator_hi=h["hi"], rel_hl=hr["hl"], rel_lo=hr["lo"],
                rel_hi=hr["hi"],
                ch2_prediction="metallurgy stronger => positive",
                holds=bool(hr["lo"] > 0)))
            print(f"  {y:.0f}  shift 1% of (alpha_win + alpha_dr) from direct "
                  f"reuse to metallurgy:")
            print(f"        d {ind:<10s} = {h['hl']:+.6f} "
                  f"[{h['lo']:+.6f}, {h['hi']:+.6f}]   "
                  f"({100*hr['hl']:+.4f}% [{100*hr['lo']:+.4f},"
                  f"{100*hr['hi']:+.4f}])")
    pd.DataFrame(ch2_rows).to_csv(
        os.path.join(args.out, "wp2d_ch2_route_ranking.csv"), index=False)
    verdict = "FAILS" if all(r["rel_hi"] < 0 for r in ch2_rows) else (
        "HOLDS" if all(r["rel_lo"] > 0 for r in ch2_rows) else "MIXED")
    print(f"  Ch2's ranking (metallurgy stronger than direct reuse): "
          f"**{verdict}** on the estimated zinc A(t) at both ends of the "
          f"window.")
    print(f"  Direct reuse is the stronger route: the metallurgy route loses "
          f"(1 - tau_waelz) = "
          f"{100*(1-np.median(P[:, 0, 5])):.0f}% ({years[0]:.0f}) / "
          f"{100*(1-np.median(P[:, -1, 5])):.0f}% ({years[-1]:.0f}) of its "
          f"flow and\n  re-enters at Refined, so the returned material pays "
          f"the manufacturing loss a second time.")

    # --- persist ------------------------------------------------------------
    os.makedirs(args.out, exist_ok=True)
    indicator_table(frozen, nonauto, years, seeds).to_csv(
        os.path.join(args.out, "wp2d_indicators.csv"), index=False)
    disc.to_csv(os.path.join(args.out, "wp2d_discrepancy.csv"), index=False)
    el.to_csv(os.path.join(args.out, "wp2d_elasticities.csv"), index=False)

    arrays = dict(years=years, seeds=seeds, mu_cohorts=mu,
                  state_names=np.array(STATE, object),
                  flow_names=np.array(L.FLOW_NAMES, object),
                  param_names=np.array(L.PARAM_NAMES, object),
                  rules=np.array(L.RULES, object),
                  tau_frozen=tau_fr, N_frozen=N,
                  prob_reaches_use=pu,
                  dtau_dparams=dtau,
                  source_md5=np.array(md5), n_sub=np.array(args.n_sub),
                  ref_rule=np.array(REF_RULE, object))
    for k in L.FLOW_NAMES:
        arrays[f"count_frozen_{k}"] = cnt_fr[k]
        arrays[f"dcount_dparams_{k}"] = dcounts[k]
    for rule, v in nonauto.items():
        arrays[f"tau_nonauto_{rule}"] = v["tau"]
        arrays[f"end_stable_{rule}"] = v["end_stable"]
        arrays[f"t_switch_{rule}"] = np.array(v["t_switch"])
        for k in L.FLOW_NAMES:
            arrays[f"count_nonauto_{rule}_{k}"] = v["counts"][k]
    np.savez_compressed(os.path.join(args.out, "wp2d_circularity.npz"),
                        **arrays)

    fig_circularity(frozen, nonauto, years, d["mask_test"],
                    os.path.join(args.out, "wp2d_circularity.png"))
    fig_elasticities(el, years, os.path.join(args.out,
                                             "wp2d_elasticities.png"))
    print(f"\nwrote wp2d_* to {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
