#!/usr/bin/env python3
"""
zinc_market_lab.py — lab module for WP-11e (market dynamics) and WP-11f
(attenuation bias)
=======================================================================

Two work packages share one question: *what does annual observation do to
structure that lives inside the year?*  WP-11e asks it about a Chapter-3
cobweb oscillation and about whether an annually-fitted model can reproduce
short-run dynamics at all; WP-11f asks it about the bias the same operator
induces in the published alpha estimates.  Both need the same three objects,
so they live here.

  1. **A Chapter-3 cobweb**, solved rather than asserted.  Gambaro et al.
     (2025) Eqs. (18)-(21)/(24)-(25) with the reference parameters of their
     Table 2, integrated as a delay system on the twin's own 1980-2019 window
     with the real GDP growth rate as the exogenous forcing `r(t)`.  The
     output is a price path whose oscillation *period is generated by the
     lead time* and is not a free knob, which is the whole point of the
     Ch. 3 link.

  2. **A Fourier bridge into the twin.**  `zinc_synth_lab.make_truth_nn_eval`
     already accepts an arbitrary list of `(channel, frequency, amplitude,
     phase)` log-additive components through its `season` argument.  A cobweb
     path is projected onto that basis, so a market oscillation is injected
     through the *verified* generator rather than through a second one, and
     every WP-3 operator check still applies unchanged.  The truncation error
     is measured, not assumed.

  3. **Spectral operators in closed form and measured.**  The period integral
     is a boxcar of width `Delta`, transfer `|sinc(pi f Delta)|`, exact nulls
     at `f = k/Delta`; point sampling has unit gain and folds `f` to
     `|f - round(f Delta)/Delta|`.  Stocks and flows therefore lose sub-annual
     structure in *opposite* ways, which is the mechanism WP-11e reports and
     the first of the two mechanisms WP-11f separates.

Pattern
-------
Follows `zinc_fisher_lab.py` / `zinc_voi_lab.py` (CLAUDE.md rule 1).
`zinc_colloc_v5.py` is imported and never edited, and `PATCHES` is empty:
everything is composed from `zinc_synth_lab`'s public pieces and the core's
own RHS.  Weights, where a fitted model is needed, are reloaded from the
`zinc_A_lab` dumps; nothing here refits.

What is *not* claimed
---------------------
The cobweb is a Ch. 3-style oscillator embedded in the twin, not a joint
estimate of the market and the cycle.  Its amplitude is a pre-registered
elasticity times a normalised waveform; its *frequency* is the object under
test and comes from the delay.  Section 5 of `run_wp11e.py` states which
lead times are the paper's own and which are the short-lead extrapolation.

CLI
---
    python zinc_market_lab.py --check
"""

from __future__ import annotations

import argparse
import json
import os
import sys

import numpy as np

import zinc_synth_lab as S
from zinc_alpha_lab import integrity_check, load_anchor_config      # noqa: F401

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_DIR_DEFAULT = os.path.join(HERE, "analysis")
SYNTH_DIR = os.path.join(HERE, "analysis", "synth")
WEIGHTS_DIR_DEFAULT = os.path.join(HERE, "analysis", "wp2a")

PATCHES: list[str] = []

ALPHA_NAMES = S.ALPHA_NAMES

# ---------------------------------------------------------------------------
# Chapter 3 — Gambaro et al. (2025), Resources Policy 103, 105548.
# ---------------------------------------------------------------------------
# Reference-case parameters, Table 2.  Units as published: `c` and the delays
# in years, `eta` in bn$/Tg, `delta` in bn$/yr, the `k` and `z` dimensionless.
# `z_R` is not in Table 2 (only `z_E` is); the recycling branch is given the
# same value, which is stated here rather than hidden in the code.
CH3 = dict(
    c=1.6,            # price sensitivity to relative excess demand   [1/yr]
    eta=3.1,          # price impact on demand growth                 [bn$/Tg]
    k_E=0.60,         # extraction response gain                      [-]
    k_R=0.55,         # recycling response gain                       [-]
    z_E=0.85,         # share of new demand met when price falls      [-]
    z_R=0.85,         # not in Table 2; set equal to z_E              [-]
    delta=0.53,       # intrinsic price trend                         [bn$/yr]
    tau_E=8.0,        # mining lead time, reference case              [yr]
    tau_R=2.0,        # recycling response delay                      [yr]
)

# Initial conditions, Table 3 (the copper reference case, t = 0 at 1961).
# The magnitudes matter: `dP/dt = c P (Q-S)/Q + delta` is proportional to the
# price *level*, so solving in normalised units would change the realised
# period.  They are used unchanged here, and the fact that they are calibrated
# to copper rather than to zinc is a stated approximation — the twin needs a
# plausible Ch. 3-style oscillator, not a joint estimate of the zinc market.
CH3_IC = dict(P0=3.2, Q0=6.3, E0=4.0, R0=2.3)   # bn$/Tg, Tg/yr, Tg/yr, Tg/yr

# The paper's own sweep range for the mining lead time (Sec. 5.1: "from the
# 8 years of the reference case ... reduced down to 2 years and prolonged to
# 32 years").  Anything below 2 yr is an extrapolation *outside* the paper's
# range and is labelled as such wherever it is used.
CH3_TAU_PUBLISHED = (2.0, 4.0, 8.0, 16.0, 32.0)
CH3_TAU_SHORT = (0.25, 0.5, 1.0)          # inventory/logistics scale, ours

# Where the market enters the cycle.  Pre-registered before any curve was
# looked at.  Signs follow Ch. 3's own economics: a price rise pulls scrap
# into the recycling routes hardest (the two old-scrap channels), pulls on
# refined offtake weakly and negatively (substitution / demand destruction,
# Ch. 3 Eq. 21's `eta` term), and moves the smelter draw on concentrate only
# a little.  Magnitudes are elasticities of log(alpha) w.r.t. log(price).
MARKET_ELASTICITY = {
    "alpha_cc": +0.10,
    "alpha_refc": -0.08,
    "alpha_win": +0.35,
    "alpha_dr": +0.30,
}

# Fourier bridge: how many components per channel, and the reconstruction
# tolerance the bridge must meet before a dataset built on it is usable.
N_FOURIER_DEFAULT = 24
FOURIER_TOL = 0.10           # rel. L2 error of the truncated reconstruction

# ---------------------------------------------------------------------------
# The WP-11e arms.  Frequency is the treatment; amplitude is held fixed.
# ---------------------------------------------------------------------------
# Both arms carry the *same* realised log-price volatility, so the only thing
# that differs between them is where the market oscillation sits relative to
# the annual observation window.  The common level is the reference case's own
# realised `rms(log P)`, so the size of the signal is Ch. 3's and not a choice
# made to suit the answer.
#
# `mkt_ref`  the published reference case: tau_E = 8 yr, c = 1.6 /yr.  The
#            cycle it generates is multi-decadal and sits far inside the
#            annual Nyquist band.
# `mkt_fast` the same equations in the regime a *warehouse-inventory* market
#            occupies rather than a mining-investment one: a lead time of
#            three months and a price loop that clears roughly thirty times
#            faster.  This is outside Ch. 3's own parameter range and is
#            labelled as an extrapolation wherever it is reported; it is the
#            only way the Ch. 3 mechanism produces a sub-annual cycle at all,
#            which is itself one of WP-11e's findings.
MARKET_ARMS = {
    "mkt_ref": dict(tau_E=8.0, tau_R=2.0, params={}, n_keep=24,
                    published=True),
    "mkt_fast": dict(tau_E=0.25, tau_R=0.25, params=dict(c=50.0), n_keep=96,
                     published=False),
}
MARKET_RMS_LOGP = None      # filled by `arm_solution`, = mkt_ref's own rms


def arm_solution(ctx, arm, *, n_sub=S.N_SUB):
    """The cobweb solution for a named WP-11e arm, plus its season list
    rescaled to the common log-price volatility."""
    spec = MARKET_ARMS[arm]
    ref = cobweb_solve(ctx, n_sub=n_sub)                 # the reference case
    rms_ref = float(np.std(ref["osc"]))
    sol = (ref if arm == "mkt_ref" else
           cobweb_solve(ctx, tau_E=spec["tau_E"], tau_R=spec["tau_R"],
                        params=spec["params"], n_sub=n_sub))
    scale = rms_ref / max(float(np.std(sol["osc"])), 1e-12)
    season, fc = market_season(sol, amplitude=scale, n_keep=spec["n_keep"])
    return dict(arm=arm, sol=sol, season=season, fourier=fc,
                amplitude_scale=scale, rms_logP=rms_ref,
                published=spec["published"],
                period=dominant_period(sol))


# WP-11f bias-surface grid.  Frequencies straddle the annual boxcar nulls
# (1, 2, 3 /yr are exact nulls) and the point-sampling Nyquist (0.5 /yr).
BIAS_FREQS = (0.35, 0.65, 1.00, 1.35, 2.00, 2.70, 3.00, 4.35)
# Log amplitudes in nats.  0.02 nats is a +-2% swing; 0.40 is +-49%.
BIAS_AMPS = (0.02, 0.05, 0.10, 0.20, 0.40)
# Phase is a nuisance parameter at non-harmonic frequencies: the bias at a
# given (f, a) depends on where the year boundary falls in the cycle, so
# every cell is averaged over these and the spread is reported.
BIAS_PHASES = (0.0, np.pi / 2, np.pi, 3 * np.pi / 2)


def install(v5mod=None):
    """No-op: this module patches nothing.  Present for interface parity with
    the other lab modules, and it installs `zinc_synth_lab`'s dispatcher so a
    twin can be armed from here."""
    return S.install(v5mod)


# ===========================================================================
# 1. the Chapter 3 cobweb
# ===========================================================================
def gdp_growth(ctx):
    """Real GDP growth rate on the twin's annual grid, from the dataset.

    `r(t)` in Ch. 3 Eq. (21).  Resolved by explicit name through
    `zinc_synth_lab.DRIVER_ALIASES` (CLAUDE.md rule 2), never by position.
    """
    cols = list(ctx["exog_cols"])
    j = cols.index(S.DRIVER_ALIASES["GDP"])
    g = np.asarray(ctx["exog_values"][:, j], float)
    yrs = np.asarray(ctx["years"], float)
    r = np.zeros_like(g)
    r[1:] = np.diff(np.log(np.maximum(g, 1e-12))) / np.diff(yrs)
    r[0] = r[1]
    return yrs, r


def cobweb_solve(ctx, *, tau_E=None, tau_R=None, n_sub=S.N_SUB, params=None,
                 P0=None, Q0=None, E0=None, R0=None, hist_slope=0.0):
    """Integrate Ch. 3 Eqs. (18)-(21)/(24)-(25) on the twin's window.

    Fixed-step RK4 on the twin's own `n_sub`-per-year grid with linear
    interpolation of the history at the delayed arguments — the paper solves
    the same system with Hermite interpolation at the delays; the difference
    is O(h^2) against O(h^4) *in the delayed lookup only*, and `check()`
    measures the grid convergence rather than assuming it.

    The switched right-hand side (supply follows price when price is rising,
    and follows demand otherwise) is Eq. (24)'s discontinuity and is kept as
    written; it is what makes the cycle asymmetric.

    Returns `t, P, Q, E, R` plus the realised oscillation diagnostics.
    """
    p = dict(CH3)
    p.update(params or {})
    tau_E = float(p["tau_E"] if tau_E is None else tau_E)
    tau_R = float(p["tau_R"] if tau_R is None else tau_R)

    P0 = CH3_IC["P0"] if P0 is None else float(P0)
    Q0 = CH3_IC["Q0"] if Q0 is None else float(Q0)
    E0 = CH3_IC["E0"] if E0 is None else float(E0)
    R0 = CH3_IC["R0"] if R0 is None else float(R0)

    yrs, r_ann = gdp_growth(ctx)
    t = S.fine_grid(yrs, n_sub)
    h = 1.0 / float(n_sub)
    n = t.size

    # Pre-history: the delayed arguments reach back before t0, so the price
    # history is extended as a constant (Ch. 3's own "state variables
    # containing delays were assumed to be constant" initial condition).
    P = np.empty(n); Q = np.empty(n); E = np.empty(n); R = np.empty(n)
    P[0], Q[0], E[0], R[0] = P0, Q0, E0, R0

    def _hist_P(s, i_now):
        """P at time `s <= t[i_now]`, linearly interpolated on the solved
        prefix; constant extrapolation with slope `hist_slope` before t0."""
        if s <= t[0]:
            return P0 * np.exp(hist_slope * (s - t[0]))
        k = min(int((s - t[0]) / h), i_now)
        if k >= i_now:
            return P[i_now]
        w = (s - t[k]) / h
        return (1.0 - w) * P[k] + w * P[k + 1]

    def _gp(s, i_now):
        """`(1/P) dP/dt` at the delayed time `s` — Ch. 3's `g_p`."""
        a = _hist_P(s - 0.5 * h, i_now)
        b = _hist_P(s + 0.5 * h, i_now)
        m = _hist_P(s, i_now)
        return (b - a) / h / max(m, 1e-12)

    r_of = lambda s: float(np.interp(s, yrs, r_ann))

    def deriv(i, s, P_i, Q_i, E_i, R_i):
        Sup = E_i + R_i
        dP = p["c"] * P_i * (Q_i - Sup) / max(Q_i, 1e-12) + p["delta"]
        dQ = (p["eta"] / max(P_i, 1e-12)) * r_of(s) * Q_i
        gE = _gp(s - tau_E, i)
        gR = _gp(s - tau_R, i)
        dE = p["k_E"] * gE * E_i if gE > 0.0 else p["k_E"] * p["z_E"] * dQ
        dR = p["k_R"] * gR * R_i if gR > 0.0 else p["k_R"] * p["z_R"] * dQ
        return dP, dQ, dE, dR

    for i in range(n - 1):
        y = (P[i], Q[i], E[i], R[i])
        k1 = deriv(i, t[i], *y)
        y2 = tuple(v + 0.5 * h * d for v, d in zip(y, k1))
        k2 = deriv(i, t[i] + 0.5 * h, *y2)
        y3 = tuple(v + 0.5 * h * d for v, d in zip(y, k2))
        k3 = deriv(i, t[i] + 0.5 * h, *y3)
        y4 = tuple(v + h * d for v, d in zip(y, k3))
        k4 = deriv(i, t[i] + h, *y4)
        P[i + 1], Q[i + 1], E[i + 1], R[i + 1] = [
            v + (h / 6.0) * (a + 2 * b + 2 * c + d)
            for v, a, b, c, d in zip(y, k1, k2, k3, k4)]
        P[i + 1] = max(P[i + 1], 1e-9)
        E[i + 1] = max(E[i + 1], 1e-12)
        R[i + 1] = max(R[i + 1], 1e-12)
        Q[i + 1] = max(Q[i + 1], 1e-12)

    logP = np.log(P)
    # Detrend: the market *oscillation* is what annual observation is being
    # asked about, not the secular price trend, which the drivers already
    # carry.  A straight line in log price is removed and reported.
    A = np.column_stack([np.ones_like(t), t - t[0]])
    beta, *_ = np.linalg.lstsq(A, logP, rcond=None)
    osc = logP - A @ beta

    if not np.all(np.isfinite(P)):
        raise FloatingPointError(
            f"cobweb diverged at tau_E={tau_E}, c={p['c']}: the switched RHS "
            f"of Eq. (24) is stiff in the explosive regime and needs a finer "
            f"grid than n_sub={n_sub}")

    return dict(t=t, P=P, Q=Q, E=E, R=R, log_price=logP, osc=osc,
                trend=beta, tau_E=tau_E, tau_R=tau_R, n_sub=int(n_sub),
                params={k: float(v) for k, v in p.items()},
                ic=dict(P0=P0, Q0=Q0, E0=E0, R0=R0))


def dominant_period(sol, *, f_lo=1.0 / 40.0, f_hi=None):
    """Period of the detrended log-price oscillation, two ways.

    The record is only ~39 yr, so a multi-decadal cobweb completes one or two
    cycles in it and an FFT peak lands on a record-length harmonic whether or
    not the oscillation is real.  The **zero-crossing** period is therefore
    reported alongside and is the one quoted: `2 x span / n_crossings` needs
    no bin alignment.  They agree to within a bin whenever both are meaningful
    and disagree loudly when the FFT is reading its own grid.
    """
    t, y = sol["t"], sol["osc"]
    h = t[1] - t[0]
    f_hi = 0.5 / h if f_hi is None else f_hi
    Y = np.fft.rfft(y - y.mean())
    f = np.fft.rfftfreq(y.size, d=h)
    p = np.abs(Y) ** 2
    m = (f >= f_lo) & (f <= f_hi)
    if not np.any(m):
        return dict(f_peak=np.nan, period_yr=np.nan, share=np.nan)
    k = np.argmax(np.where(m, p, -np.inf))
    sgn = np.sign(y - y.mean())
    nz = int(np.sum(sgn[1:] * sgn[:-1] < 0))
    span = float(t[-1] - t[0])
    per_zc = 2.0 * span / nz if nz > 0 else np.inf
    return dict(f_peak=float(f[k]),
                period_fft_yr=float(1.0 / f[k]) if f[k] > 0 else np.inf,
                period_yr=float(per_zc), n_crossings=nz,
                cycles_in_record=float(span / per_zc) if np.isfinite(per_zc) else 0.0,
                share=float(p[k] / max(p[m].sum(), 1e-30)),
                rms_log=float(np.std(y)))


# ===========================================================================
# 2. the Fourier bridge into the twin
# ===========================================================================
def fourier_components(t, y, *, n_keep=N_FOURIER_DEFAULT, t0=None):
    """Project `y(t)` onto `sum_k a_k sin(2 pi f_k (t - t0) + ph_k)`.

    A real DFT over the window, keeping the `n_keep` largest-amplitude
    non-zero bins.  Returns `(f, a, ph)` arrays and the relative L2 error of
    the truncated reconstruction, which is the number that has to be small
    before a twin built on this bridge means anything.
    """
    t = np.asarray(t, float).ravel()
    y = np.asarray(y, float).ravel()
    t0 = float(t[0] if t0 is None else t0)
    h = t[1] - t[0]
    n = y.size - 1                      # drop the duplicate endpoint
    yy = y[:n] - y[:n].mean()
    Y = np.fft.rfft(yy) / n
    f = np.fft.rfftfreq(n, d=h)
    amp = 2.0 * np.abs(Y)
    amp[0] = 0.0
    if n % 2 == 0:
        amp[-1] = np.abs(Y[-1])
    # rfft convention: y ~ sum amp_k * cos(2 pi f_k (t - t[0]) + angle(Y_k))
    # and cos(x) = sin(x + pi/2), so the sine phase is angle + pi/2.
    ph = np.angle(Y) + 0.5 * np.pi
    order = np.argsort(-amp)[:int(n_keep)]
    order = order[amp[order] > 0.0]
    fk, ak, pk = f[order], amp[order], ph[order]
    # phases are referenced to t[0]; shift to the requested t0
    pk = pk + 2.0 * np.pi * fk * (t[0] - t0)
    rec = np.zeros_like(t)
    for fi, ai, pi_ in zip(fk, ak, pk):
        rec += ai * np.sin(2.0 * np.pi * fi * (t - t0) + pi_)
    err = float(np.linalg.norm(rec - (y - y.mean()))
                / max(np.linalg.norm(y - y.mean()), 1e-30))
    return dict(f=fk, a=ak, phase=pk, rel_l2=err, recon=rec)


def market_season(sol, *, elasticity=None, amplitude=1.0,
                  n_keep=N_FOURIER_DEFAULT, t0=None, channels=None):
    """A `zinc_synth_lab` `season` list carrying the cobweb oscillation.

    `amplitude` rescales the whole waveform so the *shape and frequency* come
    from the delay system while the size is a stated design choice; setting it
    to 1.0 uses the cobweb's own realised log-price amplitude.
    """
    t0 = float(S.TRUTH["season_t0"] if t0 is None else t0)
    el = dict(MARKET_ELASTICITY if elasticity is None else elasticity)
    if channels is not None:
        el = {k: v for k, v in el.items() if k in channels}
    fc = fourier_components(sol["t"], sol["osc"], n_keep=n_keep, t0=t0)
    season = []
    for chan, e in el.items():
        for fi, ai, pi_ in zip(fc["f"], fc["a"], fc["phase"]):
            season.append((chan, float(fi), float(e * amplitude * ai),
                           float(pi_)))
    return season, fc


# ===========================================================================
# 3. spectral operators
# ===========================================================================
def sinc_gain(f, delta):
    """`|sinc(pi f Delta)|` — the boxcar (period-integral) transfer, with
    exact nulls at `f = k/Delta`.  Spec section 1, consequence 3."""
    x = np.pi * np.asarray(f, float) * float(delta)
    return np.abs(np.where(np.abs(x) < 1e-12, 1.0, np.sin(x) / np.where(x == 0, 1.0, x)))


def alias_freq(f, delta):
    """Where a component at `f` lands after point sampling at spacing `Delta`.

    Point sampling has unit gain and no nulls: it *folds* rather than
    annihilates.  A component at exactly `k/Delta` folds to 0 — it becomes a
    constant offset in the sampled series, which is the opposite of what the
    same component does to a period-integrated one.
    """
    f = np.asarray(f, float)
    fs = 1.0 / float(delta)
    r = np.mod(f, fs)
    return np.minimum(r, fs - r)


def project_amplitude(t, y, f, *, t0=0.0):
    """Least-squares amplitude and phase of a single frequency in `y(t)`.

    Phase-safe: an FFT bin only lines up with `f` when `f` is a harmonic of
    the record length, and every non-harmonic frequency in this package is
    chosen precisely because it is not.  Two-column regression instead.
    """
    t = np.asarray(t, float).ravel()
    y = np.asarray(y, float).ravel()
    w = 2.0 * np.pi * float(f) * (t - t0)
    A = np.column_stack([np.ones_like(t), t - t0, np.sin(w), np.cos(w)])
    beta, *_ = np.linalg.lstsq(A, y, rcond=None)
    s, c = beta[2], beta[3]
    return dict(amp=float(np.hypot(s, c)), phase=float(np.arctan2(c, s)),
                level=float(beta[0]), slope=float(beta[1]))


def band_power(t, y, *, f_cut, detrend=True):
    """Share of the variance of `y(t)` above `f_cut`, on a uniform grid."""
    t = np.asarray(t, float).ravel()
    y = np.asarray(y, float).ravel()
    if detrend:
        A = np.column_stack([np.ones_like(t), t - t[0]])
        beta, *_ = np.linalg.lstsq(A, y, rcond=None)
        y = y - A @ beta
    h = t[1] - t[0]
    n = y.size - 1
    Y = np.fft.rfft(y[:n] - y[:n].mean())
    f = np.fft.rfftfreq(n, d=h)
    p = np.abs(Y) ** 2
    tot = p.sum()
    hi = p[f > f_cut].sum()
    return dict(total=float(tot), above=float(hi),
                share_above=float(hi / max(tot, 1e-30)),
                rms=float(np.std(y)))


# ===========================================================================
# 4. the alpha-target bias, decomposed into its two mechanisms
# ===========================================================================
# WP-11f asks for the bias surface with the two mechanisms separated:
#
#   (i)  **attenuation.**  The period integral is a boxcar, so what the data
#        can report about a sub-annual component is `|sinc(pi f Delta)|` times
#        its true amplitude.  For a *log*-additive oscillation this is not
#        only a loss of amplitude: the window mean of `A exp(a sin)` exceeds
#        `A exp(mean(a sin))` by the Jensen gap, exactly `log I_0(a)` over a
#        whole number of cycles, so annual observation of an oscillating
#        coefficient reports a level that is biased *upward* by `~a^2/4`
#        regardless of frequency.  That is a bias, not a variance.
#
#   (ii) **target construction.**  `alpha_obs = F_int / trapz(S)` is an
#        integral over an interpolated point stock, which introduces the
#        within-window `Cov_w(alpha, S)/mean_w(S)` term and a trapezoid
#        quadrature term.  WP-3 established the identity; this reuses it.
#
# Both are measured against the same reference so they add.
def jensen_log_bias(a):
    """`log I_0(a)`: the exact log-level bias of a full-cycle average of
    `exp(a sin)`.  `~a^2/4` for small `a`."""
    from numpy import i0
    return np.log(i0(np.asarray(a, float)))


def bias_cell(ctx, *, freq, amp, phase, delta=1.0, channels=None,
              arm_name="base", dense=None):
    """One cell of the WP-11f surface: all four channels driven at `(freq,
    amp, phase)`, observed at window width `delta`.

    Returns, per channel and in log units so the components add:

      `attenuation`  log(window-mean alpha) - log(alpha_true at the node)
                     — what period integration does to the reported level,
                     including the Jensen gap and the year-end placement;
      `covariance`   log(exposure-weighted mean) - log(unweighted mean)
                     — the within-window F-S covariance term;
      `quadrature`   log(alpha_obs) - log(exposure-weighted mean)
                     — the trapezoid stock exposure;
      `total`        log(alpha_obs) - log(alpha_true at the node).

    Driving all four channels in one solve rather than one at a time follows
    `run_wp3.part2b_amplitude_sweep`.  The channels then share a perturbed
    trajectory, so a small cross-channel term is folded into each cell; it is
    second order in `amp` and `check()` bounds it.
    """
    chans = list(ALPHA_NAMES if channels is None else channels)
    season = [(c, float(freq), float(amp), float(phase)) for c in chans]
    if dense is None:
        dense = S.dense_solve(ctx, arm_name, season=season)
    b = S.alpha_target_bias(ctx, dense, delta, arm_name=arm_name, season=season)

    # alpha_true at the node the model is supervised at: the closing year of
    # the window (`_build_empirical_alphas` stores the window average at the
    # closing year — WP-3's "year-end placement" finding).
    idx = S._window_indices(dense, delta)
    tc = S.truth_coefficients(ctx, dense["t"][idx[1:]], arm_name,
                              S_path=dense["S4"][idx[1:]], season=season)
    a_node = tc["alphas"]                                   # (nW, 4)

    lg = lambda x: np.log(np.maximum(np.asarray(x, float), 1e-30))
    out = {}
    for k, name in enumerate(ALPHA_NAMES):
        att = lg(b["a_unweighted"][:, k]) - lg(a_node[:, k])
        cov = lg(b["a_weighted"][:, k]) - lg(b["a_unweighted"][:, k])
        quad = lg(b["a_obs"][:, k]) - lg(b["a_weighted"][:, k])
        tot = lg(b["a_obs"][:, k]) - lg(a_node[:, k])
        out[name] = dict(attenuation=att, covariance=cov, quadrature=quad,
                         total=tot, years=b["years"])
    return out, dense


# ===========================================================================
# 5. evaluating a fitted model continuously
# ===========================================================================
def coeff_path(fit, params, t_grid, S_path=None, data=None):
    """The fitted model's reported coefficients at *arbitrary* times.

    The UDE is a continuous-time model, so `alpha_hat(t)` is defined between
    the annual nodes it was fitted at.  That is exactly what WP-11e's second
    question needs: an annually-fitted model can be *asked* for monthly
    dynamics, and the question is whether what comes back is signal or the
    shape of `exog_fn`'s interpolation.

    Returns `alphas` (T, 4), `tau_sup` (T, 8), `f_cohort` (T, 3), `cp` (T,).
    """
    import jax
    import jax.numpy as jnp

    d = fit.data_all if data is None else data
    t_grid = np.asarray(t_grid, float).ravel()
    if S_path is None:
        S_obs = np.asarray(d["stocks_obs"], float)
        yrs = np.asarray(d["years"], float).ravel()
        S_path = np.column_stack([np.interp(t_grid, yrs, S_obs[:, j])
                                  for j in range(S_obs.shape[1])])
    S_path = np.asarray(S_path, float)

    @jax.jit
    def one(t, Sx):
        ex = __import__("zinc_colloc_v5").exog_fn(t, d["exog_times"],
                                                  d["exog_values"])
        o = fit.nn_eval(params, t, Sx, ex, d)
        tau_sup = jnp.concatenate([o["taus"],
                                   jnp.array([o["frac_fu"][0], o["frac_fu"][1],
                                              o["frac_eu"][0], o["frac_eu"][1]])])
        return o["alphas"], tau_sup, o["f_cohort"], o["cp"]

    A, T8, FC, CP = jax.vmap(one)(jnp.asarray(t_grid), jnp.asarray(S_path))
    return dict(t=t_grid, alphas=np.asarray(A), tau_sup=np.asarray(T8),
                f_cohort=np.asarray(FC), cp=np.asarray(CP))


def load_fit_and_params(seed, weights_dir=WEIGHTS_DIR_DEFAULT, cfg=None,
                        data=None):
    """A zero-step `fit` plus the Stage-B weights of `seed`.  No refit."""
    import zinc_cf_lab as cflab
    fit = cflab.init_fit(cfg=cfg, seed=int(seed))
    params = cflab.load_params(os.path.join(weights_dir, f"A_seed{seed}.npz"))
    return fit, params


# ===========================================================================
# 6. real-data coarsening (WP-11b's observation-side arm)
# ===========================================================================
# WP-6b coarsens the *record* and refits; that is 528 fits and is not
# available.  What is available without a single fit is the coarsening of the
# **target**, on the real data, through the core's own operators — flows are
# additive over windows so an annual record aggregates exactly to Delta = 2,
# 5, 10, stocks are point-read at the retained nodes, and `alpha_obs` is
# rebuilt by `_build_empirical_alphas` at each width.  The same statistic is
# computable on the twin, where the truth is known.  Comparing the two curves
# is a like-for-like check of whether the twin reproduces the real record's
# response to coarsening on the observation side.
def coarsen_real(delta, *, cfg=None, start_aligned=True):
    """The real dataset re-expressed at window width `delta` (years).

    `delta` must be an integer number of years: the real record is annual and
    a coarser window is an exact sum of annual flow integrals.  Stocks are
    point-read at the retained year boundaries.  Returns the coarsened
    `alpha_obs` together with the annual reference aggregated the same way,
    so the two are directly comparable.
    """
    import zinc_colloc_v5 as v5

    step = int(round(float(delta)))
    if abs(step - float(delta)) > 1e-9 or step < 1:
        raise ValueError(f"delta={delta} is not a whole number of years; the "
                         f"real record is annual and cannot be refined")
    cfg = dict(cfg or load_anchor_config())
    loader = S._ORIG_LOADER or v5.load_zinc_data
    raw = loader(cfg["xlsx_path"], extra_exog_cols=cfg.get("extra_exog_cols"))

    yrs = np.asarray(raw["years"], float).ravel()
    S_obs = np.asarray(raw["stocks_obs"], float)
    F_obs = np.asarray(raw["flows_obs"], float)            # (T-1, n_obs_flows)
    pred_idx = list(np.asarray(raw["flow_obs_to_pred_idx"], int))

    # the four alpha parent flows, in v5.FLOW_NAMES indices 1..4
    cols = [pred_idx.index(j) for j in (1, 2, 3, 4)]
    Fp = F_obs[:, cols]                                     # (T-1, 4)

    nW = (yrs.size - 1) // step
    keep = np.arange(nW + 1) * step
    if not start_aligned:
        keep = keep + ((yrs.size - 1) - nW * step)
    t_nodes = yrs[keep]
    S_pt = S_obs[keep]
    F_int = np.stack([Fp[keep[i]:keep[i + 1]].sum(axis=0) for i in range(nW)])

    F_for_alpha = np.zeros((t_nodes.size, 4))
    F_for_alpha[1:] = F_int
    alpha = v5._build_empirical_alphas(t_nodes, S_pt, F_for_alpha)
    return dict(years=t_nodes, delta=float(step), alpha_obs=alpha,
                stocks_obs=S_pt, F_int=F_int, keep=keep,
                alpha_names=list(v5.ALPHA_NAMES))


def coarsen_twin(dense, ctx, delta):
    """The same coarsening applied to the twin, with the truth alongside."""
    samp = S.sample(dense, float(delta), ctx, noise_scale=0.0)
    return dict(years=samp["years"], delta=float(delta),
                alpha_obs=samp["alpha_obs"], stocks_obs=samp["stocks_obs"],
                F_int=samp["F_int"])


# ===========================================================================
# check
# ===========================================================================
def check(verbose=True, n_sub_ref=192):
    """Everything that must hold before any WP-11e/f number is believed."""
    import zinc_colloc_v5 as v5

    res = {}
    integrity_check()
    install(v5)
    cfg = load_anchor_config()
    ctx = S.driver_context(cfg)

    if verbose:
        print("--- resolved drivers (by name, never by position) ---")
        for short, name in S.DRIVER_ALIASES.items():
            print(f"  {short:9s} -> {name!r}  "
                  f"[col {list(ctx['exog_cols']).index(name)}]")
        n_ex = len(ctx["exog_cols"])
        orders = len(cfg.get("exog_feature_orders", (0, 1)))
        print(f"  exog columns = {n_ex}, feature orders = {orders}, "
              f"input_dim = {1 + 4 + n_ex * orders}")
        print(f"  (CLAUDE.md rule 2 asserts input_dim == 23; the anchor_v4 "
              f"config gives {1 + 4 + n_ex * orders} — SCHEMA §9 flag 1, "
              f"still open)")

    # ---- 1. the cobweb solves and oscillates, and the delay sets the period
    sol = cobweb_solve(ctx)
    dp = dominant_period(sol)
    res["cobweb_period_ref_yr"] = dp["period_yr"]
    res["cobweb_period_ref_fft_yr"] = dp["period_fft_yr"]
    res["cobweb_cycles_in_record"] = dp["cycles_in_record"]
    res["cobweb_rms_log_price"] = dp["rms_log"]
    res["cobweb_finite"] = bool(np.all(np.isfinite(sol["P"])))

    # grid convergence of the delayed solve
    sol2 = cobweb_solve(ctx, n_sub=2 * S.N_SUB)
    i2 = np.searchsorted(sol2["t"], sol["t"])
    res["cobweb_grid_rel"] = float(np.max(np.abs(sol2["osc"][i2] - sol["osc"]))
                                   / max(np.std(sol["osc"]), 1e-12))

    # shortening the lead time must shorten the cycle (Ch. 3 Sec. 5.1)
    per = {}
    for te in CH3_TAU_PUBLISHED:
        per[te] = dominant_period(cobweb_solve(ctx, tau_E=te))["period_yr"]
    # The zero-crossing period is quantised at `2 x span / n`, and a
    # multi-decadal cycle makes only two to six crossings in a 39-yr record,
    # so the estimator resolves the period to about one bin.  Monotonicity is
    # therefore only testable where the bins are far enough apart; below
    # tau_E = 4 yr it is not resolvable and is reported, not gated.
    _tail = [t for t in CH3_TAU_PUBLISHED if t >= 4.0]
    res["period_nondecreasing_tau_ge_4"] = bool(
        all(per[a] <= per[b] + 1e-9 for a, b in zip(_tail, _tail[1:])))
    res["periods_by_tau"] = {str(k): float(v) for k, v in per.items()}
    # The floor: no lead time in or below the paper's range makes the Ch. 3
    # oscillation sub-annual.  This is a finding, checked as an invariant.
    res["min_period_over_tau_yr"] = float(min(
        dominant_period(cobweb_solve(ctx, tau_E=te))["period_yr"]
        for te in tuple(CH3_TAU_SHORT) + tuple(CH3_TAU_PUBLISHED)))
    res["ch3_never_subannual"] = bool(res["min_period_over_tau_yr"] > 1.0)

    # ---- 2. the Fourier bridge reconstructs the cobweb
    for arm in MARKET_ARMS:
        a = arm_solution(ctx, arm)
        res[f"fourier_rel_l2_{arm}"] = a["fourier"]["rel_l2"]
        res[f"period_{arm}_yr"] = a["period"]["period_yr"]
        res[f"rms_logP_{arm}"] = float(np.std(a["sol"]["osc"]) * a["amplitude_scale"])
    res["fourier_ok"] = bool(all(res[f"fourier_rel_l2_{a}"] <= FOURIER_TOL
                                 for a in MARKET_ARMS))

    # ---- 3. spectral operators against their closed forms
    #   the boxcar annihilates harmonics of the window and attenuates the rest
    res["sinc_null_1yr"] = float(sinc_gain(1.0, 1.0))
    res["sinc_null_2yr"] = float(sinc_gain(2.0, 1.0))
    res["sinc_135"] = float(sinc_gain(1.35, 1.0))
    #   measured on a pure tone integrated over unit windows
    t = np.linspace(0.0, 40.0, 40 * 96 + 1)
    for f in (1.0, 1.35, 2.70):
        y = np.sin(2 * np.pi * f * t + 0.7)
        c = np.concatenate([[0.0], np.cumsum(0.5 * (y[1:] + y[:-1]) * (t[1] - t[0]))])
        k = np.arange(0, t.size, 96)
        win = (c[k[1:]] - c[k[:-1]])              # unit-window integrals
        mid = 0.5 * (t[k[1:]] + t[k[:-1]])
        got = project_amplitude(mid, win, f)["amp"]
        res[f"boxcar_gain_meas_f{f}"] = float(got)
        res[f"boxcar_gain_form_f{f}"] = float(sinc_gain(f, 1.0))
    #   point sampling folds instead of annihilating
    res["alias_1yr_point"] = float(alias_freq(1.0, 1.0))
    res["alias_135_point"] = float(alias_freq(1.35, 1.0))
    res["alias_270_point"] = float(alias_freq(2.70, 1.0))

    # ---- 4. Jensen gap in closed form against a numerical average
    a = 0.4
    u = np.linspace(0.0, 2 * np.pi, 20001)
    num = np.log(np.trapezoid(np.exp(a * np.sin(u)), u) / (2 * np.pi))
    res["jensen_gap_rel_err"] = float(abs(num - jensen_log_bias(a))
                                      / max(abs(num), 1e-30))

    # ---- 5. real-data coarsening is an exact re-aggregation
    c1 = coarsen_real(1)
    raw_alpha = None
    loader = S._ORIG_LOADER or v5.load_zinc_data
    raw = loader(cfg["xlsx_path"], extra_exog_cols=cfg.get("extra_exog_cols"))
    raw_alpha = np.asarray(raw["alpha_obs"], float)
    m = np.isfinite(raw_alpha) & np.isfinite(c1["alpha_obs"])
    res["coarsen_real_d1_vs_loader"] = float(
        np.max(np.abs(c1["alpha_obs"][m] - raw_alpha[m])))
    c2 = coarsen_real(2)
    # flow integrals at Delta=2 must equal the sum of the two annual ones
    res["coarsen_real_flow_sum"] = float(np.max(np.abs(
        c2["F_int"] - (c1["F_int"][0::2][:c2["F_int"].shape[0]]
                       + c1["F_int"][1::2][:c2["F_int"].shape[0]]))))

    # ---- 6. cross-channel contamination in `bias_cell`
    #   driving all four channels at once vs one at a time, at the largest
    #   amplitude on the grid: the gap bounds the shared-trajectory term.
    cells_all, _ = bias_cell(ctx, freq=1.35, amp=BIAS_AMPS[-1], phase=0.0)
    cells_one, _ = bias_cell(ctx, freq=1.35, amp=BIAS_AMPS[-1], phase=0.0,
                             channels=["alpha_win"])
    res["bias_cross_channel_max_log"] = float(np.max(np.abs(
        cells_all["alpha_win"]["total"] - cells_one["alpha_win"]["total"])))

    if verbose:
        print("\n--- zinc_market_lab check ---")
        for k, v in res.items():
            print(f"  {k:34s} {v}")
        print(f"\n  patches installed: {S.PATCHES}")
    return res


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args(argv)
    if a.check:
        r = check(verbose=True)
        json.dump({k: (v if not isinstance(v, dict) else v) for k, v in r.items()},
                  sys.stdout, indent=2, default=float)
        print()
        return 0
    ap.print_help()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
